version: "3.2"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        depends_on:
            - worker 
            - chat
    worker:
        build:
            context: .
            dockerfile: jobsity_stockWorker/Dockerfile
    chat:
        build:
            context: .
            dockerfile: jobsity_chat/Dockerfile
        ports: 
            - '5000:80'
        depends_on: 
            - worker
        